version: '3.7'

networks:
  web:

services:
  api:
    build:
      context: .
    volumes:
      - .:/var/www/api
    environment:
      - API_SECRET_KEY=foobar
    command: bash -c "npm run prod"
    networks:
      - web
    ports:
      - 4000:4000
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 5
        window: 120s
    healthcheck:
      test: ["CMD", "curl", "-XGET", "http://api:4000/graphql?query={test}"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

  webserver:
    image: nginx:1.16.1
    restart: on-failure
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - web
    ports:
      - 80:80
    links:
      - api
    depends_on:
      - api

